-- Binary System
INSERT INTO BYTEMATH.PAGE (ID, IDENTIFIER, COURSE_ID)
VALUES (1, 'BINARY_SYSTEM_INTRO', 1);

INSERT INTO BYTEMATH.PAGE (ID, IDENTIFIER, COURSE_ID)
VALUES (2, 'BINARY_SYSTEM_CONVERTING', 1);

INSERT INTO BYTEMATH.PAGE (ID, IDENTIFIER, COURSE_ID)
VALUES (3, 'BINARY_SYSTEM_ARITHMETIC', 1);


-- Logical Operands
INSERT INTO BYTEMATH.PAGE (ID, IDENTIFIER, COURSE_ID)
VALUES (4, 'LOGICAL_OPERANDS_INTRO', 2);

INSERT INTO BYTEMATH.PAGE (ID, IDENTIFIER, COURSE_ID)
VALUES (5, 'LOGICAL_OPERANDS_BASIC_OPERATORS', 2);

INSERT INTO BYTEMATH.PAGE (ID, IDENTIFIER, COURSE_ID)
VALUES (6, 'LOGICAL_OPERANDS_ADVANCED_OPERATORS', 2);



-- Graph Theory
INSERT INTO BYTEMATH.PAGE (ID, IDENTIFIER, COURSE_ID)
VALUES (8, 'GRAPH_THEORY_INTRO', 3);

INSERT INTO BYTEMATH.PAGE (ID, IDENTIFIER, COURSE_ID)
VALUES (9, 'GRAPH_THEORY_DIFFERENT_GRAPHS', 3);

INSERT INTO BYTEMATH.PAGE (ID, IDENTIFIER, COURSE_ID)
VALUES (10, 'GRAPH_THEORY_GRAPH_TRAVERSALS', 3);

INSERT INTO BYTEMATH.PAGE (ID, IDENTIFIER, COURSE_ID)
VALUES (11, 'GRAPH_THEORY_ALGORITHMS', 3);


-- Number Theory
INSERT INTO BYTEMATH.PAGE (ID, IDENTIFIER, COURSE_ID)
VALUES (12, 'NUMBER_THEORY_INTRO', 4);

INSERT INTO BYTEMATH.PAGE (ID, IDENTIFIER, COURSE_ID)
VALUES (13, 'NUMBER_THEORY_LCM_GCD', 4);

INSERT INTO BYTEMATH.PAGE (ID, IDENTIFIER, COURSE_ID)
VALUES (14, 'NUMBER_THEORY_RSA', 4);

INSERT INTO BYTEMATH.PAGE (ID, IDENTIFIER, COURSE_ID)
VALUES (15, 'NUMBER_THEORY_MODULAR_ARITHMETIC', 4);
