INSERT INTO BYTEMATH.COURSE (ID, NAME)
VALUES (1, 'BINARY_SYSTEM');

INSERT INTO BYTEMATH.COURSE (ID, NAME)
VALUES (2, 'LOGICAL_OPERANDS');

INSERT INTO BYTEMATH.COURSE (ID, NAME)
VALUES (3, 'GRAPH_THEORY');

INSERT INTO BYTEMATH.COURSE (ID, NAME)
VALUES (4, 'NUMBER_THEORY');
