CREATE TABLE BYTEMATH.QUIZ
(
    ID              BIGINT DEFAULT NEXTVAL('BYTEMATH.BYTEMATH_GLOBAL_SEQUENCE') PRIMARY KEY,
    IDENTIFIER VARCHAR(255),
    LANGUAGE   VARCHAR(3),
    TITLE      VARCHAR(255)
);

CREATE TABLE BYTEMATH.QUESTION
(
    ID              BIGINT DEFAULT NEXTVAL('BYTEMATH.BYTEMATH_GLOBAL_SEQUENCE') PRIMARY KEY,
    QUESTION_TEXT VARCHAR(255),
    QUESTION_TYPE VARCHAR(255),
    QUIZ_ID       BIGINT NOT NULL,
    FOREIGN KEY (QUIZ_ID) REFERENCES BYTEMATH.QUIZ (ID)

);

CREATE TABLE BYTEMATH.ANSWER
(
    ID              BIGINT DEFAULT NEXTVAL('BYTEMATH.BYTEMATH_GLOBAL_SEQUENCE') PRIMARY KEY,
    ANSWER_TEXT VARCHAR(255),
    QUESTION_ID BIGINT NOT NULL,
    IS_CORRECT  BOOLEAN,
    FOREIGN KEY (QUESTION_ID) REFERENCES BYTEMATH.QUESTION (ID) ON DELETE CASCADE
);
