INSERT INTO BYTEMATH.COURSE (ID, NAME)
VALUES (1, 'Binary System');

INSERT INTO BYTEMATH.COURSE (ID, NAME)
VALUES (2, 'Logical Operands');

INSERT INTO BYTEMATH.COURSE (ID, NAME)
VALUES (3, 'Graph Theory');

INSERT INTO BYTEMATH.COURSE (ID, NAME)
VALUES (4, 'Number Theory');
