INSERT INTO BYTEMATH.PAGE (ID, IDENTIFIER)
VALUES (1, 'BINARY_SYSTEM_INTRO');

INSERT INTO BYTEMATH.PAGE (ID, IDENTIFIER)
VALUES (2, 'LOGICAL_OPERANDS_INTRO');

INSERT INTO BYTEMATH.PAGE (ID, IDENTIFIER)
VALUES (3, 'GRAPH_THEORY_INTRO');
