version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: bytemath
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  bytemath-service:
    build: ./bytemath-service
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bytemath
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres
    ports:
      - "1111:1111"
    restart: always

  bytemath-ui:
    build: ./bytemath-ui
    environment:
      - REACT_APP_API_URL=http://localhost:1111
    ports:
      - 3000:3000

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/bytemath
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=password
      - KC_HEALTH_ENABLED=true
    command:
      - start-dev
      - --import-realm
    volumes:
      - './keycloak/themes/custom-theme/theme:/opt/keycloak/themes'
      - './keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json'
    depends_on:
      - postgres
    restart: always

volumes:
  postgres-data:
