spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bytemath
          jwk-set-uri: http://localhost:8080/realms/bytemath/protocol/openid-connect/certs
  application:
    name: bytemath-service
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 1111

---
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:bytemath
    username: sa
    password: password
    driverClassName: org.h2.Driver
---

spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:postgresql://postgres:5432/bytemath
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/bytemath
          jwk-set-uri: http://keycloak:8080/realms/bytemath/protocol/openid-connect/certs
---
