spring:
  application:
    name: bytemath-service

server:
  port: 1111

---
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:bytemath
    username: sa
    password: password
    driverClassName: org.h2.Driver
---

spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
---
